create table [PostsWithDeleted] (
	[Id] int NOT NULL,
	[PostTypeId] tinyint NOT NULL,
	[AcceptedAnswerId] int NULL,
	[ParentId] int NULL,
	[CreationDate] datetime NOT NULL,
	[DeletionDate] datetime NULL,
	[Score] int NOT NULL,
	[ViewCount] int NULL,
	[Body] TEXT NULL,
	[OwnerUserId] int NULL,
	[OwnerDisplayName] nTEXT NULL,
	[LastEditorUserId] int NULL,
	[LastEditorDisplayName] nTEXT NULL,
	[LastEditDate] datetime NULL,
	[LastActivityDate] datetime NULL,
	[Title] nTEXT NULL,
	[Tags] nTEXT NULL,
	[AnswerCount] int NULL,
	[CommentCount] int NULL,
	[FavoriteCount] int NULL,
	[ClosedDate] datetime NULL,
	[CommunityOwnedDate] datetime NULL,
	[ContentLicense] TEXT NOT NULL
);